import {FormEvent,useEffect,useMemo,useState} from 'react'
import {CalendarDays,Check,ChevronRight,ClipboardCheck,Home,Image,LogOut,Plus,Settings,Users,X} from 'lucide-react'
import type {Session} from '@supabase/supabase-js'
import {configured,supabase} from './supabase'
import type {Checkin,Profile,Task} from './types'
import {cancelReminders,scheduleReminders} from './notifications'

const today=()=>new Date().toLocaleDateString('sv-SE')
const demoTasks:Task[]=[{id:'1',household_id:'demo',title:'吃早餐',description:'开启元气满满的一天',schedule:'daily',due_time:'09:00',active:true,created_by:'demo',created_at:''},{id:'2',household_id:'demo',title:'散步 30 分钟',description:'户外走走，记得放松',schedule:'daily',due_time:'20:00',active:true,created_by:'demo',created_at:''},{id:'3',household_id:'demo',title:'早点休息',description:'睡前放下手机',schedule:'daily',due_time:'23:00',active:true,created_by:'demo',created_at:''}]
const quotes=['今天完成的一小步，也是给自己的大大的拥抱。','慢慢来，你已经比昨天更靠近目标了。','认真生活的人，连平凡的日子也会发光。','把今天过好，就是最温柔的自律。','每一次打卡，都是在对未来的自己说：我会做到。']
function dingDong(){try{const C=window.AudioContext||((window as any).webkitAudioContext);const ctx=new C();[0,1].forEach(i=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=i?1046.5:783.99;gain.gain.setValueAtTime(.0001,ctx.currentTime+i*.16);gain.gain.exponentialRampToValueAtTime(.16,ctx.currentTime+i*.16+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+i*.16+.32);osc.connect(gain);gain.connect(ctx.destination);osc.start(ctx.currentTime+i*.16);osc.stop(ctx.currentTime+i*.16+.35)})}catch{}}

export default function App(){
 const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true)
 useEffect(()=>{if(!configured){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{subscription.unsubscribe()}},[])
 useEffect(()=>{if(session)loadProfile();else setProfile(null)},[session])
 async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',session!.user.id).single();setProfile(data)}
 if(loading)return <Splash/>
 if(!configured)return <Demo/>
 if(!session)return <Auth/>
 if(!profile?.household_id)return <Setup profile={profile} refresh={loadProfile}/>
 return <Main profile={profile}/>
}

function Splash(){return <div className="splash"><div className="logo"><Check/></div><h1>一起打卡</h1></div>}
function Auth(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[signup,setSignup]=useState(false),[msg,setMsg]=useState('')
 async function submit(e:FormEvent){e.preventDefault();setMsg('');const result=signup?await supabase.auth.signUp({email,password,options:{data:{display_name:name}}}):await supabase.auth.signInWithPassword({email,password});if(result.error)setMsg(result.error.message);else if(signup)setMsg('注册成功，请检查邮箱完成验证。')}
 return <div className="auth"><div className="auth-card"><div className="logo"><Check/></div><h1>一起打卡</h1><p>认真生活的每一天，都值得被看见。</p><form onSubmit={submit}>{signup&&<input placeholder="你的称呼" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="邮箱" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength={6} placeholder="密码（至少 6 位）" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{signup?'创建账号':'登录'}</button></form>{msg&&<div className="message">{msg}</div>}<button className="link" onClick={()=>setSignup(!signup)}>{signup?'已有账号？去登录':'第一次使用？创建账号'}</button></div></div>}

function Setup({profile,refresh}:{profile:Profile|null;refresh:()=>void}){const[mode,setMode]=useState<'choose'|'create'|'join'>('choose'),[name,setName]=useState(profile?.display_name||''),[code,setCode]=useState(''),[msg,setMsg]=useState('')
 async function create(){const invite=Math.random().toString(36).slice(2,8).toUpperCase();const{data,error}=await supabase.from('households').insert({name:'我们的打卡',invite_code:invite,owner_id:profile!.id}).select().single();if(error)return setMsg(error.message);await supabase.from('profiles').update({household_id:data.id,display_name:name,role:'owner'}).eq('id',profile!.id);refresh()}
 async function join(){const{data,error}=await supabase.rpc('join_household',{code:code.toUpperCase(),chosen_name:name});if(error||!data)return setMsg(error?.message||'邀请码不存在');refresh()}
 return <div className="auth"><div className="auth-card"><h2>把两个人连接起来</h2>{mode==='choose'?<><button onClick={()=>setMode('create')}>创建我们的打卡空间</button><button className="secondary" onClick={()=>setMode('join')}>加入已有打卡空间</button></>:<><input placeholder="你的称呼" value={name} onChange={e=>setName(e.target.value)}/>{mode==='join'&&<input placeholder="6 位邀请码" value={code} maxLength={6} onChange={e=>setCode(e.target.value)}/>}<button onClick={mode==='create'?create:join}>{mode==='create'?'创建并获取邀请码':'加入'}</button><button className="link" onClick={()=>setMode('choose')}>返回</button></>}{msg&&<div className="message">{msg}</div>}</div></div>}

 function Main({profile}:{profile:Profile}){const[tasks,setTasks]=useState<Task[]>([]),[checks,setChecks]=useState<Checkin[]>([]),[tab,setTab]=useState<'today'|'history'|'people'>('today'),[editing,setEditing]=useState<Task|null|undefined>(),[invite,setInvite]=useState(''),[celebration,setCelebration]=useState<string|null>(null)
 const load=async()=>{const[{data:t},{data:c},{data:h}]=await Promise.all([supabase.from('tasks').select('*').eq('active',true).order('created_at'),supabase.from('checkins').select('*,profiles(display_name)').gte('checkin_date',new Date(Date.now()-30*864e5).toLocaleDateString('sv-SE')),supabase.from('households').select('invite_code').single()]);setTasks(t||[]);setChecks(c||[]);setInvite(h?.invite_code||'')}
  useEffect(()=>{load();scheduleReminders();const channel=supabase.channel('shared').on('postgres_changes',{event:'*',schema:'public'},load).subscribe();return()=>{supabase.removeChannel(channel)}},[])
 const doneIds=new Set(checks.filter(c=>c.checkin_date===today()).map(c=>c.task_id)),done=doneIds.size,total=tasks.length
  async function checkin(task:Task,file?:File,note?:string){let photo_url=null;if(file){const path=`${profile.household_id}/${crypto.randomUUID()}-${file.name}`;const{error}=await supabase.storage.from('checkin-photos').upload(path,file);if(error){alert(error.message);return false}photo_url=path}const{error}=await supabase.from('checkins').insert({task_id:task.id,user_id:profile.id,checkin_date:today(),note:note||null,photo_url});if(error){alert(error.message);return false}load();dingDong();setCelebration(quotes[Math.floor(Math.random()*quotes.length)]);window.setTimeout(()=>setCelebration(null),3600);return true}
 return <div className="app"><header><div><span className="eyebrow">{new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</span><h1>今天也要好好生活</h1></div><button className="icon-btn" onClick={()=>supabase.auth.signOut()}><LogOut/></button></header><main>{tab==='today'&&<><section className="progress-card"><div><small>今日完成</small><strong>{done}<i> / {total}</i></strong><p>{done===total&&total?'全部完成，真棒！':'每完成一件，今天就更闪亮一点'}</p></div><div className="ring" style={{'--p':`${total?done/total*360:0}deg`} as any}><span>{total?Math.round(done/total*100):0}%</span></div></section><div className="section-title"><h2>今日打卡</h2><button onClick={()=>setEditing(null)}><Plus/>新建</button></div><div className="task-list">{tasks.map(t=><TaskCard key={t.id} task={t} done={doneIds.has(t.id)} onCheck={checkin} onEdit={()=>setEditing(t)}/>)}</div></>}{tab==='history'&&<History checks={checks} tasks={tasks}/>} {tab==='people'&&<People invite={invite} profile={profile} switchSpace={async()=>{await supabase.from('profiles').update({household_id:null,role:'member'}).eq('id',profile.id);window.location.reload()}}/>}</main><nav><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}><Home/>今天</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><CalendarDays/>记录</button><button className={tab==='people'?'active':''} onClick={()=>setTab('people')}><Users/>我们</button></nav>{editing!==undefined&&<TaskModal task={editing} profile={profile} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);load()}}/>}{celebration&&<Celebration text={celebration}/>}</div>}

function TaskCard({task,done,onCheck,onEdit}:{task:Task;done:boolean;onCheck:(t:Task,f?:File,n?:string)=>Promise<boolean>;onEdit:()=>void}){const[open,setOpen]=useState(false),[note,setNote]=useState(''),[file,setFile]=useState<File>()
 if(done)return <article className="task done"><button className="check done"><Check/></button><div><h3>{task.title}</h3><p>已完成</p></div><button className="more" onClick={onEdit}><Settings/></button></article>
  return <><article className="task"><button className="check" onClick={()=>setOpen(true)}></button><div onClick={()=>setOpen(true)}><h3>{task.title}</h3><p>{task.description||'点击完成今天的打卡'}{task.due_time&&` · ${task.due_time.slice(0,5)} 前`}</p></div><button className="more" onClick={onEdit}><ChevronRight/></button></article>{open&&<div className="overlay"><div className="sheet"><button className="close" onClick={()=>setOpen(false)}><X/></button><h2>完成「{task.title}」</h2><textarea placeholder="想说点什么？（可选）" value={note} onChange={e=>setNote(e.target.value)}/><label className="upload"><Image/> {file?file.name:'添加照片（可选）'}<input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0])}/></label><button onClick={async()=>{if(await onCheck(task,file,note))setOpen(false)}}>确认打卡</button></div></div>}</>}

function TaskModal({task,profile,close,saved}:{task:Task|null;profile:Profile;close:()=>void;saved:()=>void}){const[title,setTitle]=useState(task?.title||''),[desc,setDesc]=useState(task?.description||''),[time,setTime]=useState(task?.due_time?.slice(0,5)||'')
 async function save(){if(!title.trim())return;const values={title:title.trim(),description:desc||null,due_time:time||null,schedule:'daily',household_id:profile.household_id,created_by:profile.id};const{error}=task?await supabase.from('tasks').update(values).eq('id',task.id):await supabase.from('tasks').insert(values);if(error)alert(error.message);else saved()}
 async function remove(){if(task&&confirm('确定删除这个任务吗？')){await supabase.from('tasks').update({active:false}).eq('id',task.id);saved()}}
 return <div className="overlay"><div className="sheet"><button className="close" onClick={close}><X/></button><h2>{task?'编辑任务':'新建打卡任务'}</h2><label>任务名称<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：吃早餐"/></label><label>说明<input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="可选"/></label><label>提醒时间<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><button onClick={save}>保存</button>{task&&<button className="danger" onClick={remove}>删除任务</button>}</div></div>}

function History({checks,tasks}:{checks:Checkin[];tasks:Task[]}){const grouped=useMemo(()=>checks.reduce<Record<string,Checkin[]>>((all,item)=>{(all[item.checkin_date]??=[]).push(item);return all},{}),[checks]);return <><div className="section-title"><h2>最近 30 天</h2></div><div className="history">{Object.entries(grouped).sort(([a],[b])=>b.localeCompare(a)).map(([date,list])=><section key={date}><h3>{date}<span>{list.length} 项完成</span></h3>{list.map(c=><article key={c.id}>{c.photo_url&&<PrivatePhoto path={c.photo_url}/>}<div><strong>{tasks.find(t=>t.id===c.task_id)?.title||'已删除任务'}</strong><p>{c.profiles?.display_name} · {new Date(c.created_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</p>{c.note&&<p>{c.note}</p>}</div></article>)}</section>)}</div></>}
function PrivatePhoto({path}:{path:string}){const[url,setUrl]=useState('');useEffect(()=>{supabase.storage.from('checkin-photos').createSignedUrl(path,3600).then(({data})=>setUrl(data?.signedUrl||''))},[path]);return url?<img src={url} alt="打卡照片"/>:null}
function People({invite,profile,switchSpace}:{invite:string;profile:Profile;switchSpace:()=>void}){return <div className="people"><div className="logo"><Users/></div><h2>邀请 TA 加入</h2><p>让 TA 安装 APK、注册账号，然后输入下面的邀请码。这个码只属于你们。</p><div className="invite">{invite}</div><button onClick={()=>navigator.clipboard.writeText(invite)}>复制邀请码</button><p className="privacy">两个人的权限完全相同，都可以打卡、查看、创建和编辑任务。</p><button className="switch-space" onClick={()=>{if(confirm('切换后会离开当前空间，确定继续吗？'))switchSpace()}}>切换打卡空间</button></div>}
function Celebration({text}:{text:string}){return <div className="celebration" role="status"><div className="celebration-burst">✓</div><strong>打卡完成！</strong><span>{text}</span><div className="confetti">{Array.from({length:12},(_,i)=><i key={i} style={{'--i':i} as any}/>)}</div></div>}
function Demo(){return <div className="app"><header><div><span className="eyebrow">演示模式</span><h1>今天也要好好生活</h1></div></header><main><section className="progress-card"><div><small>今日完成</small><strong>1<i> / 3</i></strong><p>连接 Supabase 后即可真实同步</p></div><div className="ring" style={{'--p':'120deg'} as any}><span>33%</span></div></section><div className="section-title"><h2>今日打卡</h2><button><Plus/>新建</button></div><div className="task-list">{demoTasks.map((t,i)=><article className={`task ${i===0?'done':''}`} key={t.id}><button className={`check ${i===0?'done':''}`}>{i===0&&<Check/>}</button><div><h3>{t.title}</h3><p>{i===0?'已完成':`${t.description} · ${t.due_time} 前`}</p></div><ChevronRight/></article>)}</div><div className="demo-note">当前是界面预览。复制 <code>.env.example</code> 为 <code>.env</code> 并填写 Supabase 配置后启用登录和同步。</div></main></div>}
